import { GoogleGenerativeAI } from '@google/generative-ai'
import { normalizeMaInSlug, maAdvisorDateFallbackSlug, polishAutoGeneratedSlugVariableSegment } from '@/lib/slugNormalize'
import { loadIntroHistory, saveIntroEntry, extractFirstSentence, buildUsedIntrosBlock } from '@/lib/introHistory'
import { stripTitlePipeChars } from '@/lib/titleCanvasWrap'

/**
 * generateContent を順に試すモデル（429 は同一モデルで待機再試行、404 は次モデルへ）。
 * gemini-1.5-* は API / キー種別により v1beta で 404 になる報告が多いため、既定は 2.x 系のみ。
 * 上書き: 環境変数 GEMINI_MODEL_LIST にカンマ区切り（例: gemini-2.5-flash,gemini-2.0-flash）
 */
const DEFAULT_GEMINI_MODELS = [
  'gemini-2.5-flash',
  'gemini-2.5-flash-lite',
  'gemini-2.0-flash',
  'gemini-2.5-pro',
] as const

function getGeminiModelIds(): readonly string[] {
  const raw = process.env.GEMINI_MODEL_LIST?.trim()
  if (!raw) return DEFAULT_GEMINI_MODELS
  const parsed = raw.split(',').map((s) => s.trim()).filter(Boolean)
  return parsed.length > 0 ? parsed : DEFAULT_GEMINI_MODELS
}

/** SDK / Google 側のエラーをログ・ユーザー向け詳細用に1行にまとめる */
function formatGeminiCaughtError(e: unknown): string {
  if (e instanceof Error) {
    const withCause = e as Error & { cause?: unknown }
    const tail =
      withCause.cause !== undefined && withCause.cause !== null
        ? ` | cause: ${formatGeminiCaughtError(withCause.cause)}`
        : ''
    return `${e.message}${tail}`
  }
  if (e && typeof e === 'object' && 'message' in e && typeof (e as { message: unknown }).message === 'string') {
    return (e as { message: string }).message
  }
  try {
    return JSON.stringify(e)
  } catch {
    return String(e)
  }
}

function sleep(ms: number): Promise<void> {
  return new Promise(resolve => setTimeout(resolve, ms))
}

/** Google 429 応答の「Please retry in 24.9s」や RetryInfo から待機秒を読む */
function parseRetryDelaySeconds(detail: string): number | null {
  const m1 = detail.match(/Please retry in ([\d.]+)\s*s/i)
  if (m1) {
    const sec = parseFloat(m1[1]!)
    if (Number.isFinite(sec) && sec >= 0) return Math.min(sec, 120)
  }
  const m2 = detail.match(/"retryDelay"\s*:\s*"(\d+)s"/i)
  if (m2) {
    const sec = parseInt(m2[1]!, 10)
    if (Number.isFinite(sec) && sec >= 0) return Math.min(sec, 120)
  }
  return null
}

/**
 * 指定プロンプトで generateContent を実行する。
 * 429（クォータ・分間トークン上限）時は API が示す秒数だけ待って同一モデルを再試行し、
 * それでもダメなら次モデルへ。404 等でモデルが無効な場合は待たずに次モデルへ。
 */
async function generateContentWithFallback(apiKey: string, prompt: string): Promise<string> {
  const genAI = new GoogleGenerativeAI(apiKey)
  /** 初回 + 待機後1回のみ（待機25秒×多回は Vercel の関数時間制限に抵触しやすい） */
  const maxQuotaRetriesPerModel = 2
  let lastError: Error | null = null
  let lastDetail = ''

  const modelIds = getGeminiModelIds()
  for (const modelId of modelIds) {
    for (let attempt = 0; attempt < maxQuotaRetriesPerModel; attempt++) {
      try {
        const model = genAI.getGenerativeModel({ model: modelId })
        const result = await model.generateContent(prompt)
        return result.response.text()
      } catch (e) {
        lastError = e instanceof Error ? e : new Error(String(e))
        lastDetail = formatGeminiCaughtError(e)
        console.error(`[Gemini] model=${modelId} attempt=${attempt + 1}/${maxQuotaRetriesPerModel} 失敗:`, lastDetail)
        const msg = lastError.message
        const combined = `${msg}\n${lastDetail}`
        const isModelUnavailable =
          /404|NOT_FOUND|not found for API version|is not supported for generateContent|ListModels/i.test(combined)
        if (isModelUnavailable) {
          console.warn(`[Gemini] model=${modelId} は利用不可のためスキップして次モデルを試します`)
          break
        }

        const isQuota = /429|503|quota|Too Many Requests|Resource exhausted|RESOURCE_EXHAUSTED|Service Unavailable/i.test(msg) ||
          /429|503|quota|Resource exhausted|RESOURCE_EXHAUSTED|Service Unavailable/i.test(lastDetail)
        if (!isQuota) throw lastError

        const waitSec = parseRetryDelaySeconds(lastDetail)
        const canRetry = attempt < maxQuotaRetriesPerModel - 1
        if (canRetry && waitSec != null) {
          const ms = Math.ceil(waitSec * 1000) + 800
          console.warn(`[Gemini] クォータ緩和のため ${ms}ms 待機して再試行します (${modelId})`)
          await sleep(ms)
          continue
        }
        break
      }
    }
  }

  const suffix = lastDetail ? ` [詳細: ${lastDetail}]` : ''
  console.error('[Gemini] 全候補モデルで失敗', { models: [...modelIds], lastDetail })
  const quotaLike = /429|quota|RESOURCE_EXHAUSTED|Too Many Requests/i.test(lastDetail)
  const hint = quotaLike
    ? '利用上限に達している可能性があります。しばらく待つか、参照資料を減らすか、Google AI Studio で枠・課金を確認してください。'
    : 'モデル廃止・API変更・認証の問題の可能性があります。GEMINI_API_KEY と利用可能モデル（AI Studio の ListModels）を確認してください。.env に GEMINI_MODEL_LIST（カンマ区切りのモデルID）で利用可能なモデルのみ指定できます。'
  throw new Error(`Gemini API での生成に失敗しました（全候補を試行済み）。${hint}${suffix}`)
}

const TITLE_MARKER = '<<<TITLE>>>'
const BODY_MARKER = '<<<BODY>>>'

const FOOTER = `導入事例・事例集はこちらから
https://www.smartboarding.net/documents/1978/`

export interface RefinedArticle {
  refinedTitle: string
  refinedContent: string
}

export interface FirstDraftResult {
  title: string
  content: string
}

/** 一次執筆・推敲本文から監修者テキストブロックを除去する（レガシー互換） */
function stripSupervisorText(content: string): string {
  if (!content) return content
  return content
    .replace(/.*監修者：株式会社FCE 代表取締役社長 石川 淳悦.*\n?/g, '')
    .replace(/.*監修者：株式会社日本提携支援.*\n?/g, '')
    .replace(/\n{3,}/g, '\n\n')
    .trim()
}

/** PREPラベル（P/R/E/P）を本文先頭ラベルから除去する（表示崩れ防止の安全策） */
function stripPrepLabels(content: string): string {
  if (!content) return content
  return content
    .replace(
      /^\s*(?:・\s*)?(?:\*\*)?\s*[PRE]\s*[（(][^）)]+[）)]\s*[：:]\s*/gm,
      ''
    )
    .replace(
      /^\s*(?:・\s*)?(?:\*\*)?\s*P\s*[（(]\s*まとめ\s*[）)]\s*[：:]\s*/gm,
      ''
    )
}

/** 画像バナー配置のプレースホルダー指示を除去する */
function stripBannerPlaceholders(content: string): string {
  if (!content) return content
  return content.replace(/\[ここに[^\]]*画像バナーを配置\]/g, '').replace(/\n{3,}/g, '\n\n')
}

/** プロンプトと参照データから一次執筆（タイトル＋本文）を生成する */
export async function generateFirstDraftFromPrompt(
  userPrompt: string,
  targetKeyword?: string,
  dataContext?: string
): Promise<FirstDraftResult> {
  const apiKey = process.env.GEMINI_API_KEY
  if (!apiKey) throw new Error('GEMINI_API_KEY が設定されていません')

  const introHistory = await loadIntroHistory()
  const usedIntrosBlock = buildUsedIntrosBlock(introHistory)

  const prompt = `あなたはSmart Boarding（スマートボーディング）／株式会社FCEの専属・上級コンテンツストラテジストです。
以下の【参照資料】を徹底的に読み込み、当社にしか書けない実践的な記事を執筆してください。

━━━━━━━━━━━━━━━━━━━━━━━━━━━━
【Smart Boarding / FCE 固定情報】
━━━━━━━━━━━━━━━━━━━━━━━━━━━━
・末尾CTA（2行）：①「導入事例・事例集はこちらから https://www.smartboarding.net/documents/1978/」②「14日間無料トライアルはこちら https://www.smartboarding.net/trial/」をこの順で必ず含めること。
・「[ここに〜画像バナーを配置]」のようなプレースホルダー指示は絶対に出力しないこと。画像バナーの配置はシステム側で自動処理される。

■ 個人情報・機密情報の保護（最重要・違反厳禁）
・本文中に**実在の企業名（株式会社FCE・Smart Boardingを除く）・個人名・住所・電話番号**を絶対に出力しないこと。
・参照資料に社名・個人名が含まれていても、記事本文では必ず「A社（製造業・従業員約300名）」「あるサービス業」のように匿名化して言及すること。
・業種・規模・従業員数などは、特定企業を推定できない範囲でのみ使用可。
・導入事例を引用する場合は「Smart Boardingの導入企業のある事例では〜」という形式にし、固有名詞は一切使わないこと。

━━━━━━━━━━━━━━━━━━━━━━━━━━━━
【出力形式】※必ずこの形式を守ること
━━━━━━━━━━━━━━━━━━━━━━━━━━━━
・タイトルに縦棒（半角 | ・全角 ｜）を含めないこと。区切りが必要なら「と」「：」や読点でつなぐこと。
タイトル：（記事タイトル）
---
（本文）

※「---」の下には記事本文のみを記述してください。

━━━━━━━━━━━━━━━━━━━━━━━━━━━━
【執筆テーマ・指示】
━━━━━━━━━━━━━━━━━━━━━━━━━━━━
${userPrompt}

${targetKeyword?.trim() ? `ターゲットキーワード：${targetKeyword}\n※タイトルと本文の自然な箇所に必ず盛り込むこと。` : ''}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━
【参照資料】
━━━━━━━━━━━━━━━━━━━━━━━━━━━━
${dataContext?.trim() ? `
以下の資料を読み込んだ上で、下記の【資料活用ルール】に従って執筆すること。

${dataContext}
` : '（資料なし：プロンプトのみで執筆）'}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━
【資料活用ルール】※資料がある場合は必ず全て実行すること
━━━━━━━━━━━━━━━━━━━━━━━━━━━━

■ 参照資料と【執筆テーマ・指示】の優先順位（最重要）
1. 【執筆テーマ・指示】およびターゲットキーワードが、記事の主題・見出し構成・論点の最優先。参照資料は補助であり、資料の目次に従って記事を書いてはならない。
2. 参照資料に「eラーニングの効果」「研修の失敗理由」「定番の研修サイクル」などの**定番・網羅的な解説フロー**が含まれていても、それを**記事の章立てとしてなぞらない**。今回のテーマ・KWに**直接必要な事実・数値・用語・事例だけ**を抜き出して使う。
3. テーマとズレた一般論を「資料にあるから」という理由で厚く書かない。不要なセクションは設けない。
4. 「S3資料にも記載されているように」「資料によると」「社内資料では」など、**参照資料そのものを指し示すメタな言い回しは禁止**。読者向けの自然な本文に溶け込ませる。
5. 資料の断片が毎回似ていても、**今回のプロンプトで指定した切り口・論点だけ**を深掘りし、別記事と同じ見出し並びの汎用解説にしない。

■ Ahrefsデータがある場合の使い方
1. 競合記事が上位表示されているキーワードと検索意図を把握する
2. 競合記事が薄い・触れていない論点を特定する
3. その論点をSmart Boarding記事の差別化ポイントとして見出しに使う
4. 競合より詳しく・具体的に書く（文字数・事例数・具体性で上回る）
5. 競合が使っていない切り口・角度から題材にアプローチする

■ FCE・Smart Boardingの社内資料（導入支援の知見・研修設計ノウハウ等）がある場合の使い方
1. 資料中の具体的な数値・期間・業種を、**今回のテーマに関係するときだけ**本文に使う（無関係な定番統計の羅列は避ける）
2. 「〜というケースがありました」という形で実際のシーンを本文に組み込む（テーマと結びつく内容に限定）
3. 「Smart Boardingでは〜」「FCEの現場では〜」という知見として書く
4. 一般論を述べた後、必ずFCE／導入支援の現場視点でその一般論を補強または修正する（ただし上記「参照資料の優先順位」に反しないこと）
5. 資料にある数値は出典明記不要でそのまま使用してよい

■ 両方ある場合
Ahrefsで競合の弱点を特定 → FCE・Smart Boardingの知見でその弱点を埋める
という構造で記事全体を設計する

━━━━━━━━━━━━━━━━━━━━━━━━━━━━
【執筆の絶対ルール】
━━━━━━━━━━━━━━━━━━━━━━━━━━━━

❶ 導入（冒頭の2〜3文）の設計
■ あなたの仕事：
今回の記事テーマ・キーワード・想定読者（人事・研修ご担当、管理職・経営層、組織開発に関わる方）を踏まえ、
「この記事でしか使えない、この記事だからこそ意味がある一文目」を自分で考えること。
他の記事の冒頭をコピーしたような汎用的な書き出しは一切禁止。

■ 導入で禁止すること（以下に該当する書き出しは不可）：
・「近年〜」「〜が問題となっています」「〜が注目されています」などの時事導入
・「研修をやっているのに定着しない」「管理職が疲弊している」だけのありきたりの悩み列挙から始める描写
・「人材不足が深刻化している」など、どの記事にも当てはまる過度に広い社会問題導入のみで終わる描写
・「ある日突然〜」「ふと気がつくと〜」のような物語調の紋切り型
・「〜という言葉を耳にする機会が増えました」のような受動的な時事導入
・前回までの記事と同じ構造・同じ語彙の導入（下記の使用禁止リスト参照）

■ 導入で意識すること：
・読者が「お、これは今まで読んだ記事と違うな」と感じる一文目にする
・テーマに固有の具体的な場面・数字・問い・事実から入る
・「悩みの共感」以外にも、反直感的な事実提示、具体的なシーン描写、
  読者への直接的な問いかけ、業界の構造的な変化の指摘、
  意外な統計データ、現場で実際に聞いた一言の引用など、自由にアプローチしてよい
・同じメディアの他記事と並んだときに「毎回違う切り口で書いている」と感じられることが最重要

${usedIntrosBlock}

❷ Smart Boarding・FCEの視点を本文の根拠として使う
累計1,200社超の導入実績（公式サイト掲載）、LMSと対面研修のハイブリッド、人財コンサルティングとの組み合わせなど、**公式に示されている強み**を抽象的な説明の裏付けとして本文中で活用すること。
「Smart Boardingでは〜」「FCEの支援の現場では〜」という形で必ず2〜3箇所登場させること（数値は公式情報の範囲で用い、未掲載の数値は捏造しないこと）。

❸ 一般論で終わらせない
各見出しセクションで「一般的には〜」で終わる説明の後に、
必ず「Smart Boardingの導入支援では〜」「実際の研修設計では〜」という
具体・固有の情報を続けること。

❹ PREP法で各セクションを構成する
P（結論）→ R（理由）→ E（Smart Boarding・FCEの事例・具体例）→ P（まとめ）
の順で書くこと。特にE（事例）を省略しないこと。
ただし本文中に「P（結論）」「R（理由）」「E（事例）」「P（まとめ）」などのラベルは出力しないこと。

❺ 末尾は必ずCTAで締める
- まとめセクションの末尾には必ず以下の文章をそのまま使うこと（一字一句変更しないこと）：
「Smart Boarding（スマートボーディング）は、法人向けオンライントレーニングと人財コンサルティングを組み合わせ、貴社の人財育成を中長期で伴走します。eラーニングだけでなく対面研修やOJT支援まで、お気軽にご相談ください。」
- その直後に必ず「導入事例・事例集はこちらから https://www.smartboarding.net/documents/1978/」を含めること。
- さらにその次の行に「14日間無料トライアルはこちら https://www.smartboarding.net/trial/」を必ず含めること。

━━━━━━━━━━━━━━━━━━━━━━━━━━━━
【構成・文体ルール】
━━━━━━━━━━━━━━━━━━━━━━━━━━━━
- 本文は2500文字以上（資料が豊富な場合は3000文字以上を目指す）
- 見出しは「1. 」「2. 」番号付き形式、小見出しは「1-1.」形式
- 専門用語には初出時に括弧で解説（例：LMS（学習管理システム））
- マークダウン記法（##・**等）は使用しない
- 箇条書きは多用しない。文章で表現できるものは文章にする
- 文末表現のバリエーションを意識する（〜です・〜ますの繰り返しを避ける）
- 対象読者：人事・研修担当、管理職、経営層（難解な用語は必ず解説付き）

- 記事の末尾に「よくある質問（FAQ）」セクションを含めること。Q. と A. の形式で5つ程度の質問と回答を作成すること。質問はターゲットキーワードに関連するユーザーの疑問を反映したものにすること。`.trim()

  const raw = await generateContentWithFallback(apiKey, prompt)

  // **太字** は維持。斜体(*単一*)と # 見出しのみ除去
  let text = raw
    .replace(/\*\*(.+?)\*\*/g, '%%BOLD_START%%$1%%BOLD_END%%')
  text = text
    .replace(/\*(.*?)\*/g, '$1')
    .replace(/\*/g, '')
    .replace(/^#{1,6}\s+/gm, '')
  text = text
    .replace(/%%BOLD_START%%/g, '**')
    .replace(/%%BOLD_END%%/g, '**')

  const titleMatch = text.match(/タイトル：(.+)/)
  const separatorIndex = text.indexOf('---')

  if (!titleMatch && separatorIndex === -1) {
    throw new Error('生成結果の形式が不正です。再度お試しください。')
  }

  const rawTitle = titleMatch?.[1]?.trim() || ''
  const title = stripTitlePipeChars(rawTitle) || '（タイトルなし）'
  let content = separatorIndex >= 0
    ? text.slice(separatorIndex + 3).trim().replace(/^-\s*/, '')
    : text.replace(/タイトル：.+/, '').trim()

  // 本文の先頭にタイトルが残っていれば削除
  content = content.replace(/^タイトル：[^\n]+\n+/, '').trim()
  if (title !== '（タイトルなし）' && content.startsWith(title)) {
    content = content.substring(title.length).trim()
  }
  content = stripPrepLabels(content)
  content = stripBannerPlaceholders(content)

  try {
    const firstSentence = extractFirstSentence(content)
    if (firstSentence) {
      await saveIntroEntry(targetKeyword ?? '', firstSentence)
    }
  } catch (e) {
    console.warn('[IntroHistory] 保存失敗（記事生成には影響なし）:', e)
  }

  return {
    title: title || '（タイトルなし）',
    content: content || '',
  }
}

/**
 * 推敲の定量評価：推敲前後の記事品質を測定しログ出力する
 */
function measureArticleQuality(label: string, content: string): {
  boldCount: number
  numberCount: number
  avgSentenceLen: number
  sbMentions: number
  ctaPresent: boolean
} {
  const boldCount = (content.match(/\*\*[^*]+\*\*/g) ?? []).length
  const numberCount = (content.match(/\d+[%％万社件名ヶ月倍日時間]/g) ?? []).length
  const sentences = content.split(/[。！？\n]/).filter(s => s.trim().length > 5)
  const avgSentenceLen = sentences.length > 0
    ? Math.round(sentences.reduce((sum, s) => sum + s.trim().length, 0) / sentences.length)
    : 0
  const sbMentions = (content.match(/Smart Boarding|スマートボーディング|FCE/g) ?? []).length
  const ctaPresent = content.includes('smartboarding.net/documents/1978') && content.includes('smartboarding.net/trial')

  console.log(`[推敲品質] ${label}: 太字=${boldCount}, 数値=${numberCount}, 平均文長=${avgSentenceLen}字, SB言及=${sbMentions}, CTA=${ctaPresent ? '✓' : '✗'}`)
  return { boldCount, numberCount, avgSentenceLen, sbMentions, ctaPresent }
}

export async function refineArticleWithGemini(
  title: string,
  content: string,
  targetKeyword?: string
): Promise<RefinedArticle> {
  const cleanedContent = stripSupervisorText(content)

  const apiKey = process.env.GEMINI_API_KEY
  if (!apiKey) throw new Error('GEMINI_API_KEY が設定されていません')

  const beforeMetrics = measureArticleQuality('推敲前', cleanedContent)

  const prompt = `あなたはSmart Boarding（スマートボーディング）／株式会社FCEの編集長であり、BtoB SaaS領域のコンバージョンに精通したシニアマーケターです。
あなたの仕事は「文章校正」ではありません。一次執筆された記事を「マーケティング資産」に変える推敲です。

━━━━━━━━━━━━━━━━━━━━━━━━━━━━
【Smart Boarding / FCE の公式事実（使用可能な範囲）】
━━━━━━━━━━━━━━━━━━━━━━━━━━━━
以下の情報は公式サイト・公開資料に基づく事実であり、記事内で自由に活用してよい。
ただし以下に記載されていない数値や事例を捏造することは厳禁。

・法人向けオンライントレーニング × 人財コンサルティングの一体型サービス
・累計1,200社超の導入実績
・eラーニング（LMS）＋ 対面研修 ＋ OJT支援のハイブリッドモデル
・14日間無料トライアル提供中
・導入事例・事例集公開中（https://www.smartboarding.net/documents/1978/）
・新入社員〜管理職まで階層別プログラム対応
・学習進捗の可視化・レポーティング機能あり
・FCEの人財コンサルタントが研修設計〜運用を一貫伴走

━━━━━━━━━━━━━━━━━━━━━━━━━━━━
【元記事】
━━━━━━━━━━━━━━━━━━━━━━━━━━━━
タイトル：${title}

本文：
${cleanedContent}

${targetKeyword?.trim() ? `ターゲットキーワード：${targetKeyword}` : ''}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
【推敲フレームワーク：上から順に実行すること】
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

■■ PHASE 1: 検索意図の深掘り ■■

□ ターゲットKW「${targetKeyword ?? ''}」で検索するユーザーの意図を3階層で分析せよ：
  ・表層：「〜の方法を知りたい」（HOW）
  ・中層：「〜がうまくいかない原因を理解したい」（WHY）
  ・深層：「導入を社内で通すための根拠がほしい」「失敗したくない」（意思決定の障壁）
  → 一次執筆がHOW（方法）だけで終わっている場合、WHY（原因分析）と深層（導入障壁の解消）を必ず本文に組み込む

□ 見出しが教科書的な並び（「〜とは」→「メリット」→「方法」→「まとめ」）になっていないか？
  → 読者の意思決定フローに沿った構成に再構成する：
  例：「よくある失敗」→「根本原因」→「解決アプローチ」→「導入の始め方」→「FAQ」

■■ PHASE 2: Smart Boardingの独自性を「結論ファースト」で配置 ■■

□ 一般論 → Smart Boardingの独自性、の順番になっている箇所を見つけ、**順序を逆転**させよ。
  悪い例：「一般的にeラーニングは定着率が低い。Smart Boardingでは対面研修と組み合わせ〜」
  良い例：「Smart Boardingが累計1,200社超の導入で実証してきたのは、eラーニング単体ではなく対面研修・OJT支援と組み合わせることが定着の鍵だという点です。一般的なeラーニングのみの施策では〜」
  → Smart Boardingの強みを先に出し、一般論を理由として後付けする。読み飛ばされても訴求が残る構造にする。

□ 「Smart Boardingでは〜」「FCEの支援現場では〜」という言及が本文中に3〜5箇所あるか確認する。
  → 2箇所以下なら、適切なセクションに自然に追加する（ただし公式事実の範囲内のみ）。
  → 追加する際は「宣伝っぽい」表現を避け、「〜という知見があります」「〜というアプローチを採っています」のように読者にとって有用な情報として提示する。

□ 一般論だけで終わっているセクションがないか？
  → あれば、Smart Boardingがその課題にどう対応しているかを具体的に1〜2文追加する。

■■ PHASE 3: 数値・具体性の強化 ■■

□ 「効果がある」「改善される」「多くの企業」のような曖昧な表現を探す。
  → 以下の変換パターンに従って具体化する（ただし公式事実の範囲内で。架空の数値は厳禁）：
  ・「多くの企業」→「累計1,200社超の導入企業」
  ・「効果的な〜」→ 何がどう変わるのか具体的に記述（例：「受講完了率の向上」「研修後の行動変容の可視化」）
  ・「〜が重要です」→ なぜ重要かの理由を1文追加する

□ 各見出しセクションの冒頭に**太字の要約文を1文**追加する。
  ・要約の**太字1文**は、必ず「大見出し行（例: 1. 〜）の直後の次の段落」の先頭に置くこと。見出し行（1. で始まる行）と同一行に太字を詰め込まないこと
  ・良い例：大見出しの次に空行を挟み、その次の段落の先頭だけ「**このセクションでは、〜を解説します。**」のように1文。続けて通常の本文段落
  ・悪い例：「1. **このセクションでは…**」のように見出し行に太字を入れる、「**効果:**」「**課題:**」のようにラベル＋コロンだけを太字で連打するUI風の体裁
  → 流し読みする読者が太字1文だけで章の内容を把握できるようにする。

■■ PHASE 4: コンバージョン導線の自然な設計 ■■

□ 末尾CTAだけでなく、本文中盤に自然な誘導を1箇所挿入する。
  例：課題と解決策を提示した直後に
  「こうした導入支援の具体的な成果は、Smart Boardingの導入事例でもご覧いただけます。」
  のように、読者の理解が深まったタイミングで一度だけ自然に触れる。
  → 押し売り感を出さない。あくまで「もっと詳しく知りたい人はこちら」という情報提供の姿勢。

□ 末尾の固定CTA（下記2行）は必ず維持すること：
  ・「導入事例・事例集はこちらから https://www.smartboarding.net/documents/1978/」
  ・「14日間無料トライアルはこちら https://www.smartboarding.net/trial/」

■■ PHASE 5: 読みやすさ・感情設計 ■■

□ 冒頭2〜3文を確認し、以下のパターンに該当していたら書き直す：
  禁止：「近年〜」「〜が問題となっています」「〜が注目されています」「ある日突然〜」「〜を耳にする機会が増えました」
  → テーマ固有の具体的なシーン・反直感的な事実・読者への直接的な問いかけから始める

□ 読者の感情の流れを設計する：
  ・冒頭：共感 + 意外性（「こんな経験はありませんか？ 実は原因は〜ではなく〜にあります」）
  ・中盤：希望と具体的な道筋（「このように解決できます」）
  ・終盤：行動への後押し（「まずは無料トライアルで体験してみてください」）

□ 連続5文以上が同じ文末表現（「〜です。」「〜ます。」）にならないよう調整する。
  バリエーション：「〜です」「〜ます」「〜でしょう」「〜ください」「〜なのです」「〜ません」「〜ではないでしょうか」

□ 長い段落（5文以上の連続）があれば2〜3文ごとに改行して読みやすくする。

□ 箇条書きを使う場合は事前に数を明示する（例：「以下の3つの施策が有効です。」）

■■ PHASE 6: 品質保証（必須チェック） ■■

□ アスタリスク（*）は一切使用禁止。箇条書きは必ず「・」を使うこと。出力に * が1つも含まれないこと。
□ PREPラベル「P（結論）」「R（理由）」「E（事例）」「P（まとめ）」は本文に出力しない。
□ 「[ここに〜画像バナーを配置]」等のプレースホルダーは絶対に出力しない。
□ 「S3資料」「参照資料に」「社内資料では」などメタ表現が残っていたら読者向けの自然な文に直す。
□ 実在の企業名（株式会社FCE・Smart Boardingを除く）が含まれていたら「A社（業種・規模）」等に匿名化する。
□ 個人名・住所・電話番号が含まれていたら削除する。
□ 公式事実に記載されていない数値や導入事例の詳細を捏造していないか最終確認する。

━━━━━━━━━━━━━━━━━━━━━━━━━━━━
【出力形式】※必ずこの形式を守ること
━━━━━━━━━━━━━━━━━━━━━━━━━━━━
・タイトルに縦棒（半角 | ・全角 ｜）を含めないこと。区切りが必要なら「と」「：」や読点でつなぐこと。
タイトル：（推敲後タイトル）
---
（推敲後本文）

※「---」の下には推敲後本文のみを記述してください。`.trim()

  let text = await generateContentWithFallback(apiKey, prompt)
  // **太字** は維持。斜体(*単一*)と箇条書きの * のみ ・ に変換
  text = text.replace(/\*\*(.+?)\*\*/g, '%%BOLD_START%%$1%%BOLD_END%%')
  text = text
    .replace(/\*(.*?)\*/g, '$1')
    .replace(/^\s*\*\s+/gm, '・ ')
    .replace(/\*\s+/g, '・ ')
    .replace(/\*/g, '')
    .replace(/^#{1,6}\s+/gm, '')
  text = text
    .replace(/%%BOLD_START%%/g, '**')
    .replace(/%%BOLD_END%%/g, '**')

  const titleMatch = text.match(/タイトル：(.+)/)
  const separatorIndex = text.indexOf('---')

  if (!titleMatch && separatorIndex === -1) {
    throw new Error('推敲結果の形式が不正です。再度お試しください。')
  }

  const rawRefinedTitle = titleMatch?.[1]?.trim() || title
  const refinedTitle =
    stripTitlePipeChars(rawRefinedTitle) || stripTitlePipeChars(title) || title
  let refinedContent = separatorIndex >= 0
    ? text.slice(separatorIndex + 3).trim().replace(/^-\s*/, '')
    : text.replace(/タイトル：.+/, '').trim()

  refinedContent = refinedContent.replace(/^タイトル：[^\n]+\n+/, '').trim()
  if (refinedTitle && refinedContent.startsWith(refinedTitle)) {
    refinedContent = refinedContent.substring(refinedTitle.length).trim()
  }

  refinedContent = stripSupervisorText(refinedContent)
  refinedContent = stripPrepLabels(refinedContent)
  refinedContent = stripBannerPlaceholders(refinedContent)

  const afterMetrics = measureArticleQuality('推敲後', refinedContent)
  console.log(`[推敲改善] 太字: ${beforeMetrics.boldCount}→${afterMetrics.boldCount}, 数値: ${beforeMetrics.numberCount}→${afterMetrics.numberCount}, SB言及: ${beforeMetrics.sbMentions}→${afterMetrics.sbMentions}`)

  return {
    refinedTitle: refinedTitle || title,
    refinedContent: refinedContent || content,
  }
}

const SLUG_PREFIX = 'smartboarding-'

function sanitizeSlugSegment(raw: string): string {
  return normalizeMaInSlug(
    raw
      .trim()
      .toLowerCase()
      .replace(/[^a-z0-9\s-]/g, '')
      .replace(/\s+/g, '-')
      .replace(/-+/g, '-')
      .replace(/^-|-$/g, '')
      .slice(0, 60)
  )
}

/** 記事タイトル・本文・キーワードから SEO 向け英語スラッグを生成する（先頭は常に smartboarding- 固定、続きは本文内容に即した固有部分） */
export async function generateSlugFromGemini(
  title: string,
  targetKeyword?: string,
  articleBody?: string
): Promise<string> {
  const apiKey = process.env.GEMINI_API_KEY
  if (!apiKey?.trim()) return fallbackSlug()

  const kwPart = targetKeyword?.trim() ? `\nTarget keyword: ${targetKeyword.trim()}` : ''
  const bodyExcerpt = (articleBody ?? '').trim().slice(0, 2000)
  const bodyPart = bodyExcerpt
    ? `\nArticle body (Japanese excerpt — use this to capture the specific topic and wording):\n${bodyExcerpt}`
    : ''

  const prompt = `You are an SEO specialist. The URL slug MUST start with the fixed prefix "smartboarding-" followed by a UNIQUE English segment for this article.

You will output ONLY the variable segment: the part that comes AFTER "smartboarding-". Do NOT include "smartboarding" or "smartboarding-" in your output.

CRITICAL: Respond in English only. NEVER use Japanese characters. Output ONLY that segment, nothing else.

RULES for the variable segment (after the fixed prefix):
- Use ONLY lowercase English letters (a-z), numbers (0-9), and hyphens (-)
- 3 to 5 words separated by hyphens
- Reflect the SPECIFIC topic using BOTH the title AND the article body excerpt below (body is primary for uniqueness)
- Do NOT use Japanese, Chinese, or any non-ASCII characters
- NEVER use the standalone token "sme" — spell it out as "small-business"
- The fixed prefix "smartboarding-" already states the product; avoid repeating "smartboarding" or "boarding" inside the variable segment
- Prefer concrete topic terms: e-learning, lms, training-design, onboarding, leadership-dev, talent-management, skills, evaluation, etc.

EXAMPLES (output = variable segment only):
- Title/body about LMS introduction → lms-introduction-benefits
- Title/body about new employee onboarding training → onboarding-training-design
- Title/body about manager training → leadership-training-remote
- Title/body about measuring training effectiveness → training-roi-metrics-guide
- Title/body about HR evaluation and learning linkage → talent-evaluation-learning-cycle

Title: ${title.trim()}${kwPart}${bodyPart}

Variable segment after "smartboarding-":`

  try {
    const raw = await generateContentWithFallback(apiKey, prompt)
    let segment = sanitizeSlugSegment(raw)
    if (segment.startsWith('smartboarding-')) {
      segment = segment.slice('smartboarding-'.length).replace(/^-+/, '')
    }
    segment = segment.replace(/^smartboarding-?/, '').replace(/^-+/, '')
    if (segment.startsWith('ma-advisor-')) {
      segment = segment.slice('ma-advisor-'.length).replace(/^-+/, '')
    }
    segment = segment.replace(/^ma-advisor-?/, '').replace(/^-+/, '')
    segment = polishAutoGeneratedSlugVariableSegment(segment)
    const full = segment.length >= 3 ? `${SLUG_PREFIX}${segment}` : fallbackSlug()
    return normalizeMaInSlug(full)
  } catch (e) {
    console.warn('Gemini slug generation failed:', (e as Error)?.message)
    return fallbackSlug()
  }
}

function fallbackSlug(): string {
  return maAdvisorDateFallbackSlug()
}

/** 記事タイトル・本文から画像生成用の英文プロンプトを1文で生成する（Stable Diffusion用） */
export async function generateImagePromptFromArticle(
  title: string,
  content: string
): Promise<string> {
  const apiKey = process.env.GEMINI_API_KEY
  if (!apiKey?.trim()) throw new Error('GEMINI_API_KEY が設定されていません')

  const contentSnippet = content.trim().slice(0, 1800)
  const prompt = `You are an expert at writing Stable Diffusion prompts for Japanese B2B SaaS article thumbnails (HR, training, e-learning) aimed at the Japan market.

Read the TITLE and CONTENT below, then pick exactly ONE best-matching expression archetype from the list (by concept, not by printing its name), and output exactly ONE English prompt sentence for a photorealistic 16:9 image that evokes the article through scene, objects, light, and mood only.

ARCHETYPE CHOICES (pick one that fits the article; weave it naturally into your sentence — do not output the archetype label):
1) workspace_still_life — Neat wooden desk, notebook, coffee cup, laptop with screen showing only a minimalist pastel gradient or glow and lens blur (work, learning).
2) abstract_concept_metaphor — Symbolic objects: ascending staircase, compass, interlocking puzzle pieces with NO writing, or water ripples (growth, direction, teamwork, ideas).
3) nature_and_light — Fresh green plant leaves near a sunny window, wide empty field under blue sky, or tranquil lake horizon (potential, calm, fresh start).
4) minimalist_macro_detail — Extreme close-up on texture of premium paper, fountain pen nib, leather notebook cover, or architectural materials (quality, focus, craftsmanship).
5) architectural_lines_and_reflections — Modern office building facade, conference room structural lines with frosted glass, or daylight reflections on glass (structure, transparency, corporate tone). No signage or readable text.
6) abstract_geometric_forms — Clean compositions of soft 3D geometric shapes, layered color-blocked panels, or floating transparent spheres (harmony, systems, connection).

RULES (strict — unchanged):
- NO people, humans, silhouettes, hands, or body parts whatsoever (brand-safe empty spaces only)
- NO text, letters, numbers, logos, watermarks, signage, sticky notes with writing, printed charts, or any legible symbols anywhere in the frame
- NO UI metaphors: do NOT mention dashboards, LMS, course progress, analytics, charts, graphs, labels, tickers, HUDs, data visualizations, or "interface" of any kind
- If a laptop, monitor, or tablet appears: the screen must be described ONLY as a soft minimalist glow, blurred abstract wallpaper, or gentle gradient — never icons, chrome, windows, or readable content; use tasteful photographic bokeh or lens blur on the screen, NOT broken or glitchy LCD
- Plenty of negative space, minimalist composition, clean and calm
- Horizontal 16:9; photorealistic

COLOR PALETTE: Do NOT default to pastel. Choose ONE palette that fits the article mood from: cool blue and silver (intellectual); warm earth tones (warmth); vibrant accents (pop); monochrome with one restrained spot color (refined); or bright airy pastel (only when it truly fits). Name the palette implicitly through your color and lighting words.

Max 42 words. Output ONE English sentence only. No quotes. No explanation.

TITLE: ${title.trim()}
CONTENT EXCERPT: ${contentSnippet}

One sentence describing the scene:`

  const raw = await generateContentWithFallback(apiKey, prompt)
  const sentence = raw.trim().replace(/^["']|["']$/g, '').trim()
  return (
    sentence ||
    'clean minimalist photorealistic composition, soft natural lighting, horizontal 16:9'
  )
}
