const SLUG_PREFIX = 'smartboarding-'

/**
 * 推敲APIなどが返す「smartboarding-」以降の可変部分だけを読みやすくする。
 * 新規自動生成向け。ユーザーがカスタム入力したスラッグには適用しないこと。
 *
 * - トークン sme → small-business（略称の意味が伝わりにくいため）
 * - 単独トークン ma を除去（誤分割対策。単語一部の ma は触らない）
 */
export function polishAutoGeneratedSlugVariableSegment(segment: string): string {
  let s = segment
    .trim()
    .toLowerCase()
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '')
  if (!s) return s
  s = normalizeMaInSlug(s)
  s = s.replace(/(^|-)sme(?=-|$)/g, '$1small-business')
  let prev: string
  do {
    prev = s
    s = s.replace(/(^|-)ma(?=-|$)/g, '$1').replace(/-+/g, '-').replace(/^-|-$/g, '')
  } while (s !== prev)
  return s
}

/**
 * スラッグ内の「m-a」（M&A の誤分割）を「ma」にまとめる。
 * 例: m-a-advisor-selection → ma-advisor-selection、sme-m-a-tips → sme-ma-tips
 */
export function normalizeMaInSlug(slug: string): string {
  let prev = slug
  let next = slug.replace(/(^|-)m-a(?=-|$)/g, '$1ma')
  while (next !== prev) {
    prev = next
    next = prev.replace(/(^|-)m-a(?=-|$)/g, '$1ma')
  }
  return next
}

/** Gemini / WordPress 投稿用: API 未取得時・空スラッグ時の日付ベース英語スラッグ */
export function maAdvisorDateFallbackSlug(): string {
  const d = new Date()
  const tail = `article-${d.getFullYear()}${String(d.getMonth() + 1).padStart(2, '0')}${String(d.getDate()).padStart(2, '0')}`
  return normalizeMaInSlug(`${SLUG_PREFIX}${tail}`)
}

/**
 * REST・JSON-LD 用の最終スラッグ（英字・数字・ハイフンのみ、常に smartboarding- で開始）。
 * 空・不正・サフィックス短すぎは日付フォールバック。
 */
export function resolveCanonicalPostSlug(raw: string | undefined | null): string {
  let s = (raw ?? '').trim().toLowerCase()
  s = s.replace(/[^a-z0-9-]/g, '').replace(/-+/g, '-').replace(/^-|-$/g, '')
  if (!s) return maAdvisorDateFallbackSlug()

  if (s.startsWith(SLUG_PREFIX)) {
    // そのまま
  } else if (s.startsWith('ma-advisor')) {
    s = SLUG_PREFIX + s.slice('ma-advisor'.length).replace(/^-+/, '')
  } else if (s.startsWith('smartboarding') && !s.startsWith(SLUG_PREFIX)) {
    s = SLUG_PREFIX + s.slice('smartboarding'.length).replace(/^-+/, '')
  } else {
    s = SLUG_PREFIX + s.replace(/^-+/, '')
  }
  s = normalizeMaInSlug(s)
  const after = s.startsWith(SLUG_PREFIX) ? s.slice(SLUG_PREFIX.length) : ''
  if (after.length < 3) return maAdvisorDateFallbackSlug()
  return s
}
